@startuml

title __BOOKSHELF's Class Diagram__\n

  namespace com.example.bookshelf {
    class com.example.bookshelf.AddBookFragment {
        ~ user : FirebaseUser
        {static} - GET_CONTENT_REQUEST_CODE : int
        {static} - SCAN_ACTIVITY_REQUEST_CODE : int
        - authorEt : EditText
        - bookIm : ImageView
        - db : FirebaseFirestore
        - deletePictureBtn : Button
        - descriptionEt : EditText
        - imageUri : Uri
        - isbnEt : EditText
        - ownerUsername : String
        - photoURL : String
        - pictureBtn : Button
        - scanButton : Button
        - storage : FirebaseStorage
        - storageReference : StorageReference
        - titleEt : EditText
        - userDocumentRef : DocumentReference
        + onActivityResult()
        + onAttach()
        + onCreateDialog()
        {static} ~ newInstance()
        - chooseAndUploadPicture()
        - deletePicture()
        - scanISBN()
        - uploadPictureToDatabase()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.AddBookFragment.DialogListener {
        {abstract} + onOkPressed()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.Book {
        - BookID : String
        - author : String
        - description : String
        - isbn : Long
        - ownerUsername : String
        - photoURL : String
        - title : String
        + Book()
        + Book()
        + equals()
        + getAuthor()
        + getBookFirebaseMap()
        + getBookID()
        + getDescription()
        + getIsbn()
        + getOwnerUsername()
        + getPhotoURL()
        + getStatus()
        + getTitle()
        + hashCode()
        + setAuthor()
        + setBookID()
        + setCoverImage()
        + setDescription()
        + setIsbn()
        + setOwnerUsername()
        + setStatus()
        + setStatus()
        + setTitle()
    }
  }
  

  namespace com.example.bookshelf {
    enum BookStatus {
      Accepted
      Available
      Borrowed
      Loaned
      Requested
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.BookActivity {
        {static} + EXTRA_MESSAGE : String
        ~ storageReference : StorageReference
        - ISBN : TextView
        - author : TextView
        - bookCollection : CollectionReference
        - bookEditBtn : FloatingActionButton
        - bookId : String
        - bookRequestsBtn : FloatingActionButton
        - currentUser : FirebaseUser
        - currentUserDocument : DocumentReference
        - db : FirebaseFirestore
        - description : TextView
        - displayPic : ImageView
        - owner : TextView
        - status : TextView
        - storage : FirebaseStorage
        - title : TextView
        + onBackPressed()
        + onOkPressed()
        + onOkPressed()
        + openUserProfile()
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.BookArrayAdapter {
        - books : ArrayList<Book>
        - context : Context
        + BookArrayAdapter()
        + getView()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.BookFactory {
        ~ bookCollectionReference : CollectionReference
        ~ bookMap : Map<String, Object>
        ~ temp : ArrayList<Book>
        - db : FirebaseFirestore
        + Author()
        + CoverImage()
        + Description()
        + ISBN()
        + OwnerUsername()
        + Status()
        + Title()
        ~ BookFactory()
        ~ New()
        ~ build()
        ~ delete()
        ~ edit()
        ~ get()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.BookFactory.bookListener {
        {abstract} + getBook()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.BookRequestersViewFragment {
        ~ bookId : String
        - db : FirebaseFirestore
        - notificationCollection : CollectionReference
        - reqestsLv : ListView
        - requestsAdapter : ArrayAdapter<String>
        - requestsList : ArrayList<String>
        + onAttach()
        + onCreateDialog()
        ~ BookRequestersViewFragment()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.BookRequestersViewFragment.DialogListener {
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.BorrowMyBook {
        ~ theirUsername : String
        ~ BorrowMyBook()
        ~ scanBookConfirmReturn()
        ~ scanBookToLoan()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.BorrowTheirBook {
        ~ theirLocation : String
        ~ scanToBorrow()
        ~ scanToReturn()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.CreateAccountActivity {
        - createAccountBtn : Button
        - db : FirebaseFirestore
        - signInText : TextView
        - userAuth : FirebaseAuth
        - userEmailEt : EditText
        - userFullNameEt : EditText
        - userPasswordEt : EditText
        - userPhoneEt : EditText
        - usernameEt : EditText
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.DeleteConfirmFragment {
        - position : Integer
        + onAttach()
        + onCreateDialog()
        ~ DeleteConfirmFragment()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.DeleteConfirmFragment.DialogListener {
        {abstract} + deleteLongPress()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.EditProfileFragment {
        - fullnameEt : EditText
        - phoneEt : EditText
        + EditProfileFragment()
        + onAttach()
        + onCreateDialog()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.EditProfileFragment.OnFragmentInteractionListener {
        {abstract} + onOkPressed()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.FirebaseHelper {
        - db : FirebaseFirestore
        ~ FirebaseHelper()
        ~ add()
        ~ append()
        ~ deleteDocument()
        ~ edit()
        ~ get()
        ~ getAppUserID()
        ~ getUserID()
        ~ removeArrayItem()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.FirebaseHelper.IHelper {
        {abstract} + onFailure()
        {abstract} + onSuccess()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.ListNotifications {
        - book : String
        - db : FirebaseFirestore
        - owner : String
        - requester : String
        + ListNotifications()
        + ListNotifications()
        + getBookID()
        + getBookName()
        + getDate()
        + getMeetUpLocation()
        + getNotificationID()
        + getOwnerID()
        + getOwnerName()
        + getRequesterID()
        + getRequesterName()
        + getStatus()
        + setBook()
        + setBookName()
        + setDate()
        + setMeetUpLocation()
        + setNotificationID()
        + setOwner()
        + setOwnerName()
        + setRequester()
        + setRequesterName()
        + setStatus()
        {static} ~ get()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.MainActivity {
        ~ user : FirebaseUser
        - nextButton : Button
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.MakeRequestFragment {
        - confirmText : TextView
        + onAttach()
        + onCreateDialog()
        ~ MakeRequestFragment()
    }
  }
  

  namespace com.example.bookshelf {
    interface com.example.bookshelf.MakeRequestFragment.OnFragmentInteractionListener {
        {abstract} + onOkPressed()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.NotificationAdapter {
        - context : Context
        - notifications : ArrayList<ListNotifications>
        + NotificationAdapter()
        + getView()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.RequestDetailsActivity {
        ~ getLocation : Button
        ~ latitude : EditText
        ~ latval : Double
        ~ location : LatLng
        ~ longitude : EditText
        ~ longval : Double
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.RequestMyBook {
        ~ theirUsername : String
        ~ accept()
        ~ decline()
    }
  }
  

  namespace com.example.bookshelf {
    enum RequestStatus {
      ACCEPTED
      PENDING
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.RequestTheirBook {
        {static} ~ requestNew()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.RequestView {
        ~ accept : Button
        ~ author : TextView
        ~ decline : Button
        ~ imageView : ImageView
        ~ isbn : TextView
        ~ owner : TextView
        ~ requester : TextView
        ~ title : TextView
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.ScanISBNActivity {
        {static} - REQUEST_CAMERA_PERMISSION : int
        - barcodeData : String
        - barcodeDetector : BarcodeDetector
        - barcodeText : TextView
        - buttonOK : Button
        - buttonOKTest : Button
        - cameraSource : CameraSource
        - surfaceView : SurfaceView
        - toneGen1 : ToneGenerator
        # onCreate()
        # onPause()
        # onResume()
        - initialiseDetectorsAndSources()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.SearchBooksActivity {
        {static} + EXTRA_MESSAGE : String
        ~ user : FirebaseUser
        - db : FirebaseFirestore
        - searchBar : EditText
        - searchButton : Button
        - searchResults : ListView
        + matchBook()
        + openBookDescription()
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.SignInActivity {
        - createAccountText : TextView
        - logInBtn : Button
        - userAuth : FirebaseAuth
        - userEmailEt : EditText
        - userPassLayout : TextInputLayout
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.UserActivity {
        - cellphone : TextView
        - db : FirebaseFirestore
        - email : TextView
        - fullName : TextView
        - name : TextView
        - profilePic : ImageView
        + setProfile()
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.UserBooksActivity {
        {static} + EXTRA_MESSAGE : String
        - addBookButton : FloatingActionButton
        - bookAdapter : ArrayAdapter<Book>
        - bookCollection : CollectionReference
        - bookDataList : ArrayList<Book>
        - bookList : ListView
        - db : FirebaseFirestore
        - mStorageRef : StorageReference
        - notificationsCollection : CollectionReference
        - spinner : Spinner
        - user : FirebaseUser
        - userDocument : DocumentReference
        - userId : String
        - user_name : String
        + UserBooksActivity()
        + deleteLongPress()
        + getBook()
        + onOkPressed()
        + openBookDescription()
        # onActivityResult()
        # onCreate()
        - OwnerRequestedBooks()
        - UserBorrowedBooks()
        - UserRequestedBooks()
        - getUserOwnedBooks()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.UserInfo {
        - email : String
        - fullname : String
        - notifications : ArrayList<String>
        - ownedBooks : ArrayList<String>
        - phone : String
        - picture : String
        - username : String
        + UserInfo()
        + UserInfo()
        + UserInfo()
        + getEmail()
        + getFullname()
        + getNotifications()
        + getOwnedBooks()
        + getPhone()
        + getPicture()
        + getUserMap()
        + getUsername()
        + setEmail()
        + setFullname()
        + setNotifications()
        + setOwnedBooks()
        + setPhone()
        + setPicture()
        + setUsername()
    }
  }
  

  namespace com.example.bookshelf {
    abstract class com.example.bookshelf.UserNotification {
        ~ NotificationID : String
        ~ NotificationText : String
        ~ bookID : String
        ~ date : String
        ~ meetUpLocation : String
        ~ ownerID : String
        ~ requesterID : String
        ~ UserNotification()
        ~ asMap()
        ~ updateStatus()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.UserNotificationsActivity {
        ~ uidTv : TextView
        ~ user : FirebaseUser
        - db : FirebaseFirestore
        - notificationList : ListView
        + matchNotification()
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.UserProfileActivity {
        + user : FirebaseUser
        - db : FirebaseFirestore
        - editBtn : FloatingActionButton
        - emailTv : TextView
        - fullnameTv : TextView
        - phoneTv : TextView
        - profilePicImageV : ImageView
        - signoutBtn : Button
        - storage : FirebaseStorage
        - uri : Uri
        - usernameTv : TextView
        + onOkPressed()
        # onCreate()
    }
  }
  

  namespace com.example.bookshelf {
    class com.example.bookshelf.ViewLocationActivity {
        ~ location : LatLng
        - map : GoogleMap
        + onMapReady()
        # onCreate()
    }
  }
  

  com.example.bookshelf.AddBookFragment -up-|> androidx.fragment.app.DialogFragment
  com.example.bookshelf.AddBookFragment o-- com.example.bookshelf.AddBookFragment.DialogListener : listener
  com.example.bookshelf.AddBookFragment +-down- com.example.bookshelf.AddBookFragment.DialogListener
  com.example.bookshelf.Book .up.|> java.io.Serializable
  com.example.bookshelf.Book o-- com.example.bookshelf.Book.BookStatus : status
  com.example.bookshelf.Book +-down- com.example.bookshelf.Book.BookStatus
  com.example.bookshelf.BookActivity .up.|> com.example.bookshelf.AddBookFragment.DialogListener
  com.example.bookshelf.BookActivity .up.|> com.example.bookshelf.BookRequestersViewFragment.DialogListener
  com.example.bookshelf.BookActivity .up.|> com.example.bookshelf.MakeRequestFragment.OnFragmentInteractionListener
  com.example.bookshelf.BookActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.BookActivity o-- com.example.bookshelf.Book : currentBook
  com.example.bookshelf.BookArrayAdapter -up-|> android.widget.ArrayAdapter
  com.example.bookshelf.BookFactory o-- com.example.bookshelf.BookFactory.bookListener : listener
  com.example.bookshelf.BookFactory o-- com.example.bookshelf.Book : thisBook
  com.example.bookshelf.BookFactory +-down- com.example.bookshelf.BookFactory.bookListener
  com.example.bookshelf.BookRequestersViewFragment -up-|> androidx.fragment.app.DialogFragment
  com.example.bookshelf.BookRequestersViewFragment o-- com.example.bookshelf.BookRequestersViewFragment.DialogListener : listener
  com.example.bookshelf.BookRequestersViewFragment +-down- com.example.bookshelf.BookRequestersViewFragment.DialogListener
  com.example.bookshelf.BorrowMyBook -up-|> com.example.bookshelf.UserNotification
  com.example.bookshelf.BorrowMyBook o-- com.example.bookshelf.Book : myBook
  com.example.bookshelf.BorrowTheirBook -up-|> com.example.bookshelf.UserNotification
  com.example.bookshelf.BorrowTheirBook o-- com.example.bookshelf.Book : theirBook
  com.example.bookshelf.CreateAccountActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.CreateAccountActivity o-- com.example.bookshelf.UserInfo : userInfo
  com.example.bookshelf.DeleteConfirmFragment -up-|> androidx.fragment.app.DialogFragment
  com.example.bookshelf.DeleteConfirmFragment o-- com.example.bookshelf.DeleteConfirmFragment.DialogListener : listener
  com.example.bookshelf.DeleteConfirmFragment +-down- com.example.bookshelf.DeleteConfirmFragment.DialogListener
  com.example.bookshelf.EditProfileFragment -up-|> androidx.fragment.app.DialogFragment
  com.example.bookshelf.EditProfileFragment o-- com.example.bookshelf.EditProfileFragment.OnFragmentInteractionListener : listener
  com.example.bookshelf.EditProfileFragment o-- com.example.bookshelf.UserInfo : userInfo
  com.example.bookshelf.EditProfileFragment +-down- com.example.bookshelf.EditProfileFragment.OnFragmentInteractionListener
  com.example.bookshelf.FirebaseHelper +-down- com.example.bookshelf.FirebaseHelper.IHelper
  com.example.bookshelf.ListNotifications -up-|> com.example.bookshelf.UserNotification
  com.example.bookshelf.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.MakeRequestFragment -up-|> androidx.fragment.app.DialogFragment
  com.example.bookshelf.MakeRequestFragment o-- com.example.bookshelf.MakeRequestFragment.OnFragmentInteractionListener : listener
  com.example.bookshelf.MakeRequestFragment +-down- com.example.bookshelf.MakeRequestFragment.OnFragmentInteractionListener
  com.example.bookshelf.NotificationAdapter -up-|> android.widget.ArrayAdapter
  com.example.bookshelf.RequestDetailsActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.RequestMyBook -up-|> com.example.bookshelf.UserNotification
  com.example.bookshelf.RequestMyBook o-- com.example.bookshelf.Book : myBook
  com.example.bookshelf.RequestTheirBook -up-|> com.example.bookshelf.UserNotification
  com.example.bookshelf.RequestTheirBook o-- com.example.bookshelf.Book : theirBook
  com.example.bookshelf.RequestView -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.ScanISBNActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.SearchBooksActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.SearchBooksActivity o-- com.example.bookshelf.BookArrayAdapter : bookAdapter
  com.example.bookshelf.SignInActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.UserActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.UserBooksActivity .up.|> com.example.bookshelf.AddBookFragment.DialogListener
  com.example.bookshelf.UserBooksActivity .up.|> com.example.bookshelf.BookFactory.bookListener
  com.example.bookshelf.UserBooksActivity .up.|> com.example.bookshelf.DeleteConfirmFragment.DialogListener
  com.example.bookshelf.UserBooksActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.UserBooksActivity o-- com.example.bookshelf.BookFactory : bookFactory
  com.example.bookshelf.UserBooksActivity o-- com.example.bookshelf.FirebaseHelper : firebaseHelper
  com.example.bookshelf.UserNotification o-- com.example.bookshelf.RequestStatus : status
  com.example.bookshelf.UserNotificationsActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.UserNotificationsActivity o-- com.example.bookshelf.NotificationAdapter : notificationAdapter
  com.example.bookshelf.UserProfileActivity .up.|> com.example.bookshelf.EditProfileFragment.OnFragmentInteractionListener
  com.example.bookshelf.UserProfileActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.bookshelf.UserProfileActivity o-- com.example.bookshelf.UserInfo : userInfo
  com.example.bookshelf.ViewLocationActivity .up.|> com.google.android.gms.maps.OnMapReadyCallback
  com.example.bookshelf.ViewLocationActivity -up-|> androidx.fragment.app.FragmentActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
