@startuml

folder "books (collection)" {
file "bookID (doc)" as b {
artifact title
artifact author
artifact description
artifact isbn
artifact ownerUsername
artifact coverImage
artifact status
}
}

folder "users (collection)"  as u  {
file "userID (doc)"  {
artifact username
artifact email
artifact fullname
artifact "notifications (array)" as nu
artifact "ownedBooks (array)" as bu
artifact phone
artifact picture
}
}

folder "notifications (collection)" {
file "notificationID (doc)" as n {
artifact book
artifact date
artifact meetUpLocation
artifact owner
artifact requester
artifact status
}
}

book --> b
bu --> b
nu -up-> n

'username --> UserLookup
'owner --> UserLookup
'requester --> UserLookup
'UserLookup --> u

@enduml